# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SWIFT_RX_RAC_Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWIFT_RX_RAC_Demo
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'RxSwift-SwiftyJSON'
   pod 'RxSwiftExt'
   pod 'SnapKit'
   pod 'Alamofire'
   pod 'AlamofireImage'
   pod 'Kingfisher'
   pod 'Moya'
   pod 'RxDataSources'
   pod 'RxAlamofire'
   pod 'ObjectMapper'
#   pod 'AsyncDisplayKit'
   
end
