# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


def podThirdLib
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    
=begin
    pod 'RxSwift-SwiftyJSON'
    pod 'RxSwiftExt'
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Kingfisher'
    pod 'Moya'
    pod 'RxAlamofire'
    pod 'ObjectMapper'
=end

end

target 'SWIFT_RX_RAC_Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWIFT_RX_RAC_Demo
    podThirdLib
#   pod 'AsyncDisplayKit'
   
end
